version: '3'
services:
  app:
    image: fluxoti/php:7.4-web
    container_name: petshop
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql
  mysql:
    image: mariadb
    container_name: petshop-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: petshop
      MYSQL_ROOT_PASSWORD: 1234
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
    driver: local
